import { Inter } from 'next/font/google';
import "./globals.scss";
import s from './layout.module.scss';
//components
import Menu from "@/components/Menu/Menu";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ variable: '--font-inter', subsets: ['cyrillic'], display: 'swap' })


export default async function RootLayout({ children }) {

  return (
    <html lang="ru">

      <body className={inter.className}>

        <main className={s.main}>
          <Menu />
          <div className={s.container}>
            {children}
          </div>
        </main>

      </body>
    </html>
  );
}
